global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['sports_backend:5000']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
